"""add google_sub and totp fields to user

Revision ID: 6216e35ab071
Revises: 7ca6416ad0c0
Create Date: 2026-06-30 19:35:21.748187

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6216e35ab071'
down_revision: str | None = '7ca6416ad0c0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('google_sub', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('users', sa.Column('totp_secret', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # server_default backfills existing rows; the application always sets the
    # value explicitly so the default is only a migration-time convenience.
    op.add_column(
        'users',
        sa.Column('totp_enabled', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column('users', sa.Column('last_totp_timestep', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_google_sub'), 'users', ['google_sub'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_google_sub'), table_name='users')
    op.drop_column('users', 'last_totp_timestep')
    op.drop_column('users', 'totp_enabled')
    op.drop_column('users', 'totp_secret')
    op.drop_column('users', 'google_sub')
    # ### end Alembic commands ###
